stages:
  - test

test:
  stage: test
  image: docker:28.3
  services:
    - name: docker:28.3-dind
  variables:
    DOCKER_DRIVER: overlay2

  # Run only on
  # 1. main branch commits
  # 2. Any merge requests creation
  only:
    refs:
      - main
      - merge_requests

  before_script:
    - echo "Building Docker image"
    - docker build -t ci-showcase .

  script:
    - echo "Running tests inside container"
    - docker run --rm ci-showcase pytest app
