name: CI - Build & Test

on:
  push:
    branches: [main, dev] # Only run on key branches to reduce noise
  pull_request:
    branches: [main] # Validate PRs targeting main branch

jobs:
  test:
    runs-on: ubuntu-22.04 # Match production OS for reliability

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        # Enables advanced Docker builds
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ci-showcase .

      - name: Run tests inside container
        run: docker run --rm ci-showcase pytest app
